apiVersion: v1
kind: Service
metadata:
  name: amb-api
  labels:
    app: amb-api
spec:
  selector:
    app: amb-api
  ports:
    - port: 3334
      targetPort: http
      protocol: TCP
      name: http
